version: "3.8"

services:
  db:
    image: postgres
    container_name: portfolio_db
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdb-portfolio-data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  pgdb-portfolio-data:

networks:
  postgres-network:
    name: postgres-network
    external: true